### ISSUE TITLE
Inconsistent formatting

### ISSUE THREAD

**Issue by johnramsden** [UBC-ECE-Sasha/PIM-Embedding-Lookup#9]
This one's more of a preference thing but the current formatting is a bit inconsistent.

Can we reformat everything according to a style?

For example, I used [this `.clang-format`](https://github.com/UBC-ECE-Sasha/PIM-HDC/blob/master/PIM_HDC/.clang-format) for `PIM_HDC`, if you're happy with the styling I can reformat all the code according to it. Otherwise we can set up a new style configuration.

I'm not too concerned with what we choose for style as long as it's consistent.

**Comment by nzarif** [comment]
I have not used such a thing before. Can you elaborate more on that?

**Comment by johnramsden** [comment]
It basically auto formats your code according to configuration file settings.

**Comment by nzarif** [comment]
Nice! It does it at compile time? when we build?

**Comment by johnramsden** [comment]
It needs to be run manually, we could add something to the makefile, ie `make format` that does it. Do you have any preferences for formatting?

**Comment by nzarif** [comment]
Nice! No, I don't have any preference. Feel free to use any formatting you like.
Thanks

**Comment by johnramsden** [comment]
Instructions in #11
